name: flutterfly
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  web: ^0.5.1
  flame: ^1.18.0
  flame_audio: ^2.10.2
  get_it: ^7.7.0
  url_strategy: ^0.2.0
  oktoast: ^3.4.0
  socket_io_client: ^2.0.3+1
  intl: ^0.19.0
  dio: ^5.4.3+1
  flutter_secure_storage: ^9.2.2
  jwt_decode: ^0.3.1
  dropdown_button2: ^2.3.9
  image: ^4.2.0
  isolated_worker: ^0.1.1
  file_picker: ^8.0.3
  back_button_interceptor: ^7.0.3
  url_launcher: ^6.3.0
  linked_scroll_controller: ^0.2.0
  themed: ^5.0.3
  flutter_launcher_icons: ^0.13.1
  auto_size_text: ^3.0.0
  google_sign_in: ^6.2.1
  http: ^1.2.1
  app_links: ^6.1.1
  image_network: ^2.5.6


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  lints: ^3.0.0
  flutter_lints: ^3.0.1

flutter_launcher_icons:
  ios: true
  android: true
  image_path_android: "assets/images/flutterfly_icon.png"
  image_path_ios: "assets/images/flutterfly_icon.png"
  adaptive_icon_background: "assets/images/flutterfly_icon.png"
  adaptive_icon_foreground: "assets/images/flutterfly_icon.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  fonts:
    - family: visitor
      fonts:
        - asset: assets/fonts/visitor/visitor1.ttf
          weight: 700
        - asset: assets/fonts/visitor/visitor2.ttf
          weight: 700

  assets:
    - assets/images/pipes/pipe-green_big.png
    - assets/images/pipes/pipe-red_big.png
    - assets/images/pipes/pipe-yellow_big.png
    - assets/images/pipes/pipe-blue_big.png
    - assets/images/pipes/pipe-purple_big.png
    - assets/images/pipes/pipe-white_big.png
    - assets/images/pipes/pipe-black_big.png
    - assets/images/parallax/city_bg_3.png
    - assets/images/parallax/city_bg_4.png
    - assets/images/parallax/city_day/new_background_city_2_day.png
    - assets/images/parallax/city_day/new_background_city_2_day_2.png
    - assets/images/parallax/city_day/new_background_sky_day_gradient_4.png
    - assets/images/butterfly/flutter_fly_outline.png
    - assets/images/butterfly/flutter_fly_black.png
    - assets/images/butterfly/flutter_fly_blue.png
    - assets/images/butterfly/flutter_fly_green.png
    - assets/images/butterfly/flutter_fly_purple.png
    - assets/images/butterfly/flutter_fly_red.png
    - assets/images/butterfly/flutter_fly_white.png
    - assets/images/butterfly/flutter_fly_yellow.png
    - assets/images/butterfly/flutter_fly_outline.png
    - assets/images/butterfly/settings/flutter_fly_black_settings.png
    - assets/images/butterfly/settings/flutter_fly_blue_settings.png
    - assets/images/butterfly/settings/flutter_fly_green_settings.png
    - assets/images/butterfly/settings/flutter_fly_purple_settings.png
    - assets/images/butterfly/settings/flutter_fly_red_settings.png
    - assets/images/butterfly/settings/flutter_fly_white_settings.png
    - assets/images/butterfly/settings/flutter_fly_yellow_settings.png
    - assets/images/help_messages/message_phone_single.png
    - assets/images/help_messages/message_phone_double.png
    - assets/images/help_messages/message_web_single.png
    - assets/images/help_messages/message_web_double.png
    - assets/images/gameover.png
    - assets/images/leaderboard_image.png
    - assets/images/reddit_button.png
    - assets/images/google_button.png
    - assets/images/github_button.png
    - assets/images/score/0.png
    - assets/images/score/1.png
    - assets/images/score/2.png
    - assets/images/score/3.png
    - assets/images/score/4.png
    - assets/images/score/5.png
    - assets/images/score/6.png
    - assets/images/score/7.png
    - assets/images/score/8.png
    - assets/images/score/9.png
    - assets/images/default_avatar.png
    - assets/images/ui/game_settings_button.png
    - assets/images/ui/sound_on.png
    - assets/images/ui/sound_off.png
    - assets/images/ui/visible_on.png
    - assets/images/ui/visible_off.png
    - assets/images/ui/game_settings/player/1_butterfly.png
    - assets/images/ui/game_settings/player/2_butterflies.png
    - assets/images/default_achievement.png
    - assets/images/flutterfly_icon.png
    - assets/images/flutterfly_logo.png
    - assets/audio/die.wav
    - assets/audio/hit.wav
    - assets/audio/point.wav
    - assets/audio/wing.wav
    - assets/images/Zwaar.png
